In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import statistics

In [4]:
data = [1,1,1,2,3,4,4,4,4,5,6,7,7,7,8]

In [6]:
1+1+1+2+3+4+4+4+4+5+6+7+7+7+8

64

In [8]:
64/15

4.266666666666667

In [10]:
statistics.mean(data)

4.266666666666667

In [12]:
df = sns.load_dataset("mpg")

In [14]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [16]:
statistics.mean(df["mpg"])

23.514572864321607

In [32]:
 data = [1,1,1,2,3,4,4,4,4,5,6,7,7,7,8,50]

In [28]:
statistics.mean(data)

4.266666666666667

In [34]:
statistics.median(data)

4.0

In [40]:
statistics.mode(data)

4

In [46]:
df.mode()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,13.0,4.0,97.0,150.0,1985,14.5,73.0,usa,ford pinto
1,NaN,NaN,NaN,NaN,2130,NaN,NaN,NaN,NaN

In [48]:
len(df[df["weight"]==1985])

4

In [50]:
len(df[df["weight"]==2130])

4

# MEASURE OD DISPERSION

In [55]:
data1 = [45,42,42,41,40]
data2 = [54,48,42,33,33]

In [57]:
statistics.mean(data1)

42

statistics.mean(data2)

## RANGE
For ungrouped data, the range is the difference between the maximum and minimum values in a set of data.

In [62]:
max(data1)-min(data1)

5

In [64]:
max(data2)-min(data1)

14

## VARIANCE

The variance is a measure of how far individual(numeric)values in a dataset are from the mean or a average value.

In [71]:
statistics.variance(data1)

3.5

In [73]:
statistics.variance(data2)

85.5

## STANDARD DEVIATION
It is a square root of variance. Low values of standard deviation tell us that individual values are closer to the mean. High values, on the other hand, tell us that individual observations are far away from the mean of the data.

In [76]:
statistics.pstdev(data1)

1.6733200530681511

In [78]:
statistics.pstdev(data2)

8.270429251254132

In [80]:
df = sns.load_dataset("mpg")

In [86]:
df.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320

In [90]:
df["mpg"].max()-df["mpg"].min()

37.6

In [92]:
df["weight"].max()-df["weight"].min()

3527

In [94]:
statistics.variance(df["mpg"])

61.0896107742744

In [96]:
statistics.pstdev(df["mpg"])

7.806159061274432

In [100]:
statistics.mean(df["weight"])

2970.424623115578

In [102]:
statistics.pstdev(df["weight"])

845.7772335198175

In [104]:
df["weight"].max()

5140

In [106]:
df["weight"].min()

1613

## QUARTILES
Three points which divide the total data into four equal parts whern it has been orderly arranged are known as Quartiles.

In [109]:
age = [20,25,40,50,55,60,62]

In [111]:
statistics.median(age)

50

Q2 = 50

Q1 = 32.5

Q3 = 115/2 = 57.5

In [124]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

## COEFFICIENT OF VARIATION
The coefficient of variation is obtained by dividing the standard deviation by the mean and expressed in percentage. Symbolically, 
coefficient of variation(C.V) = SD/Mean*100

In [127]:
statistics.mean([18,12,15])

15